package com.example.evol.ui.theme

import androidx.compose.ui.graphics.Color

val DarkBackground = Color(0xFF041718)
val DarkSurface = Color(0xFF1C2B45)
val DarkSurfaceVariant = Color(0xFF243754)
val DarkPrimary = Color(0xFF1FE5DE)
val DarkPrimaryContainer = Color(0xFF165B65)
val DarkOnPrimary = Color(0xFF002425)
val DarkSecondary = Color(0xFF28CFC9)
val DarkSecondaryContainer = Color(0xFF173849)
val DarkTertiary = Color(0xFFF4B64E)
val DarkOnBackground = Color(0xFFEAF1FF)
val DarkOnSurface = Color(0xFFEAF1FF)
val DarkOnSurfaceVariant = Color(0xFF95A6BF)
val DarkOutline = Color(0xFF31445F)

val LightBackground = Color(0xFFF6F8FC)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF0F2F6)
val LightPrimary = Color(0xFF2D6BFF)
val LightPrimaryContainer = Color(0xFFE7ECF4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightSecondary = Color(0xFF4999E9)
val LightSecondaryContainer = Color(0xFFE7ECF4)
val LightTertiary = Color(0xFFF4B64E)
val LightOnBackground = Color(0xFF1E2A3B)
val LightOnSurface = Color(0xFF1E2A3B)
val LightOnSurfaceVariant = Color(0xFF8D9AAE)
val LightOutline = Color(0xFFD7DEE9)
